// 定义proto的版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/Hello.proto

// proto文件的 package,其他proto文件引用时使用

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义实体,用于作为接口请求参数
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ImgType:
	//	*Request_Jpg
	//	*Request_Png
	ImgType isRequest_ImgType `protobuf_oneof:"img_type"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_Hello_proto_rawDescGZIP(), []int{0}
}

func (m *Request) GetImgType() isRequest_ImgType {
	if m != nil {
		return m.ImgType
	}
	return nil
}

func (x *Request) GetJpg() string {
	if x, ok := x.GetImgType().(*Request_Jpg); ok {
		return x.Jpg
	}
	return ""
}

func (x *Request) GetPng() string {
	if x, ok := x.GetImgType().(*Request_Png); ok {
		return x.Png
	}
	return ""
}

type isRequest_ImgType interface {
	isRequest_ImgType()
}

type Request_Jpg struct {
	Jpg string `protobuf:"bytes,1,opt,name=jpg,proto3,oneof"`
}

type Request_Png struct {
	Png string `protobuf:"bytes,2,opt,name=png,proto3,oneof"`
}

func (*Request_Jpg) isRequest_ImgType() {}

func (*Request_Png) isRequest_ImgType() {}

// 定义实体,用于作为接口返回值
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespMessage string `protobuf:"bytes,1,opt,name=resp_message,json=respMessage,proto3" json:"resp_message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_Hello_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRespMessage() string {
	if x != nil {
		return x.RespMessage
	}
	return ""
}

var File_proto_Hello_proto protoreflect.FileDescriptor

var file_proto_Hello_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x3d, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6a, 0x70, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6a, 0x70, 0x67, 0x12, 0x12, 0x0a, 0x03, 0x70, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x70, 0x6e, 0x67, 0x42, 0x0a, 0x0a,
	0x08, 0x69, 0x6d, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2d, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73,
	0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x3e, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Hello_proto_rawDescOnce sync.Once
	file_proto_Hello_proto_rawDescData = file_proto_Hello_proto_rawDesc
)

func file_proto_Hello_proto_rawDescGZIP() []byte {
	file_proto_Hello_proto_rawDescOnce.Do(func() {
		file_proto_Hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Hello_proto_rawDescData)
	})
	return file_proto_Hello_proto_rawDescData
}

var file_proto_Hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_Hello_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: hello.Request
	(*Response)(nil), // 1: hello.Response
}
var file_proto_Hello_proto_depIdxs = []int32{
	0, // 0: hello.HelloService.SendMessage:input_type -> hello.Request
	1, // 1: hello.HelloService.SendMessage:output_type -> hello.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Hello_proto_init() }
func file_proto_Hello_proto_init() {
	if File_proto_Hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_Hello_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_Jpg)(nil),
		(*Request_Png)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Hello_proto_goTypes,
		DependencyIndexes: file_proto_Hello_proto_depIdxs,
		MessageInfos:      file_proto_Hello_proto_msgTypes,
	}.Build()
	File_proto_Hello_proto = out.File
	file_proto_Hello_proto_rawDesc = nil
	file_proto_Hello_proto_goTypes = nil
	file_proto_Hello_proto_depIdxs = nil
}
