// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user/user.proto

package com.zero.summer.pb.user;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string user_name = 2;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>bool locked = 4;</code>
   * @return The locked.
   */
  boolean getLocked();

  /**
   * <code>int32 age = 5;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>bytes buf = 6;</code>
   * @return The buf.
   */
  com.google.protobuf.ByteString getBuf();

  /**
   * <code>.google.protobuf.Timestamp send_time = 7;</code>
   * @return Whether the sendTime field is set.
   */
  boolean hasSendTime();
  /**
   * <code>.google.protobuf.Timestamp send_time = 7;</code>
   * @return The sendTime.
   */
  com.google.protobuf.Timestamp getSendTime();
  /**
   * <code>.google.protobuf.Timestamp send_time = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder();

  /**
   * <code>optional string token = 8;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>optional string token = 8;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 8;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>repeated string name_list = 9;</code>
   * @return A list containing the nameList.
   */
  java.util.List<java.lang.String>
      getNameListList();
  /**
   * <code>repeated string name_list = 9;</code>
   * @return The count of nameList.
   */
  int getNameListCount();
  /**
   * <code>repeated string name_list = 9;</code>
   * @param index The index of the element to return.
   * @return The nameList at the given index.
   */
  java.lang.String getNameList(int index);
  /**
   * <code>repeated string name_list = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the nameList at the given index.
   */
  com.google.protobuf.ByteString
      getNameListBytes(int index);

  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  int getUserInfoCount();
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  boolean containsUserInfo(
      java.lang.String key);
  /**
   * Use {@link #getUserInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getUserInfo();
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getUserInfoMap();
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  long getUserInfoOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  long getUserInfoOrThrow(
      java.lang.String key);
}
