// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user/user.proto

package com.zero.summer.pb.user;

/**
 * Protobuf type {@code user.UserRequest}
 */
public final class UserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.UserRequest)
    UserRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserRequest.newBuilder() to construct.
  private UserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserRequest() {
    userName_ = "";
    password_ = "";
    buf_ = com.google.protobuf.ByteString.EMPTY;
    token_ = "";
    nameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zero.summer.pb.user.UserProto.internal_static_user_UserRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 10:
        return internalGetUserInfo();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zero.summer.pb.user.UserProto.internal_static_user_UserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zero.summer.pb.user.UserRequest.class, com.zero.summer.pb.user.UserRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int USER_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userName_ = "";
  /**
   * <code>string user_name = 2;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string user_name = 2;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object password_ = "";
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCKED_FIELD_NUMBER = 4;
  private boolean locked_ = false;
  /**
   * <code>bool locked = 4;</code>
   * @return The locked.
   */
  @java.lang.Override
  public boolean getLocked() {
    return locked_;
  }

  public static final int AGE_FIELD_NUMBER = 5;
  private int age_ = 0;
  /**
   * <code>int32 age = 5;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  public static final int BUF_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString buf_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes buf = 6;</code>
   * @return The buf.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBuf() {
    return buf_;
  }

  public static final int SEND_TIME_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp sendTime_;
  /**
   * <code>.google.protobuf.Timestamp send_time = 7;</code>
   * @return Whether the sendTime field is set.
   */
  @java.lang.Override
  public boolean hasSendTime() {
    return sendTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp send_time = 7;</code>
   * @return The sendTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getSendTime() {
    return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp send_time = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
    return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
  }

  public static final int TOKEN_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object token_ = "";
  /**
   * <code>optional string token = 8;</code>
   * @return Whether the token field is set.
   */
  @java.lang.Override
  public boolean hasToken() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string token = 8;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>optional string token = 8;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_LIST_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList nameList_;
  /**
   * <code>repeated string name_list = 9;</code>
   * @return A list containing the nameList.
   */
  public com.google.protobuf.ProtocolStringList
      getNameListList() {
    return nameList_;
  }
  /**
   * <code>repeated string name_list = 9;</code>
   * @return The count of nameList.
   */
  public int getNameListCount() {
    return nameList_.size();
  }
  /**
   * <code>repeated string name_list = 9;</code>
   * @param index The index of the element to return.
   * @return The nameList at the given index.
   */
  public java.lang.String getNameList(int index) {
    return nameList_.get(index);
  }
  /**
   * <code>repeated string name_list = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the nameList at the given index.
   */
  public com.google.protobuf.ByteString
      getNameListBytes(int index) {
    return nameList_.getByteString(index);
  }

  public static final int USER_INFO_FIELD_NUMBER = 10;
  private static final class UserInfoDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.zero.summer.pb.user.UserProto.internal_static_user_UserRequest_UserInfoEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.SINT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> userInfo_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetUserInfo() {
    if (userInfo_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UserInfoDefaultEntryHolder.defaultEntry);
    }
    return userInfo_;
  }
  public int getUserInfoCount() {
    return internalGetUserInfo().getMap().size();
  }
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  @java.lang.Override
  public boolean containsUserInfo(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetUserInfo().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUserInfoMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getUserInfo() {
    return getUserInfoMap();
  }
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getUserInfoMap() {
    return internalGetUserInfo().getMap();
  }
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  @java.lang.Override
  public long getUserInfoOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetUserInfo().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, sint64&gt; user_info = 10;</code>
   */
  @java.lang.Override
  public long getUserInfoOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetUserInfo().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeUInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (locked_ != false) {
      output.writeBool(4, locked_);
    }
    if (age_ != 0) {
      output.writeInt32(5, age_);
    }
    if (!buf_.isEmpty()) {
      output.writeBytes(6, buf_);
    }
    if (sendTime_ != null) {
      output.writeMessage(7, getSendTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, token_);
    }
    for (int i = 0; i < nameList_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, nameList_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetUserInfo(),
        UserInfoDefaultEntryHolder.defaultEntry,
        10);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (locked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, locked_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, age_);
    }
    if (!buf_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, buf_);
    }
    if (sendTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getSendTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, token_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < nameList_.size(); i++) {
        dataSize += computeStringSizeNoTag(nameList_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNameListList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetUserInfo().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      userInfo__ = UserInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, userInfo__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zero.summer.pb.user.UserRequest)) {
      return super.equals(obj);
    }
    com.zero.summer.pb.user.UserRequest other = (com.zero.summer.pb.user.UserRequest) obj;

    if (getId()
        != other.getId()) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (getLocked()
        != other.getLocked()) return false;
    if (getAge()
        != other.getAge()) return false;
    if (!getBuf()
        .equals(other.getBuf())) return false;
    if (hasSendTime() != other.hasSendTime()) return false;
    if (hasSendTime()) {
      if (!getSendTime()
          .equals(other.getSendTime())) return false;
    }
    if (hasToken() != other.hasToken()) return false;
    if (hasToken()) {
      if (!getToken()
          .equals(other.getToken())) return false;
    }
    if (!getNameListList()
        .equals(other.getNameListList())) return false;
    if (!internalGetUserInfo().equals(
        other.internalGetUserInfo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + LOCKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLocked());
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + BUF_FIELD_NUMBER;
    hash = (53 * hash) + getBuf().hashCode();
    if (hasSendTime()) {
      hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getSendTime().hashCode();
    }
    if (hasToken()) {
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
    }
    if (getNameListCount() > 0) {
      hash = (37 * hash) + NAME_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getNameListList().hashCode();
    }
    if (!internalGetUserInfo().getMap().isEmpty()) {
      hash = (37 * hash) + USER_INFO_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUserInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zero.summer.pb.user.UserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zero.summer.pb.user.UserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zero.summer.pb.user.UserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zero.summer.pb.user.UserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zero.summer.pb.user.UserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.UserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.UserRequest)
      com.zero.summer.pb.user.UserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zero.summer.pb.user.UserProto.internal_static_user_UserRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetUserInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetMutableUserInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zero.summer.pb.user.UserProto.internal_static_user_UserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zero.summer.pb.user.UserRequest.class, com.zero.summer.pb.user.UserRequest.Builder.class);
    }

    // Construct using com.zero.summer.pb.user.UserRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      userName_ = "";
      password_ = "";
      locked_ = false;
      age_ = 0;
      buf_ = com.google.protobuf.ByteString.EMPTY;
      sendTime_ = null;
      if (sendTimeBuilder_ != null) {
        sendTimeBuilder_.dispose();
        sendTimeBuilder_ = null;
      }
      token_ = "";
      nameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      internalGetMutableUserInfo().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zero.summer.pb.user.UserProto.internal_static_user_UserRequest_descriptor;
    }

    @java.lang.Override
    public com.zero.summer.pb.user.UserRequest getDefaultInstanceForType() {
      return com.zero.summer.pb.user.UserRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.zero.summer.pb.user.UserRequest build() {
      com.zero.summer.pb.user.UserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zero.summer.pb.user.UserRequest buildPartial() {
      com.zero.summer.pb.user.UserRequest result = new com.zero.summer.pb.user.UserRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.zero.summer.pb.user.UserRequest result) {
      if (((bitField0_ & 0x00000100) != 0)) {
        nameList_ = nameList_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.nameList_ = nameList_;
    }

    private void buildPartial0(com.zero.summer.pb.user.UserRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userName_ = userName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.password_ = password_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.locked_ = locked_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.age_ = age_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.buf_ = buf_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.sendTime_ = sendTimeBuilder_ == null
            ? sendTime_
            : sendTimeBuilder_.build();
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.token_ = token_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.userInfo_ = internalGetUserInfo();
        result.userInfo_.makeImmutable();
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zero.summer.pb.user.UserRequest) {
        return mergeFrom((com.zero.summer.pb.user.UserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zero.summer.pb.user.UserRequest other) {
      if (other == com.zero.summer.pb.user.UserRequest.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getLocked() != false) {
        setLocked(other.getLocked());
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.getBuf() != com.google.protobuf.ByteString.EMPTY) {
        setBuf(other.getBuf());
      }
      if (other.hasSendTime()) {
        mergeSendTime(other.getSendTime());
      }
      if (other.hasToken()) {
        token_ = other.token_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.nameList_.isEmpty()) {
        if (nameList_.isEmpty()) {
          nameList_ = other.nameList_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureNameListIsMutable();
          nameList_.addAll(other.nameList_);
        }
        onChanged();
      }
      internalGetMutableUserInfo().mergeFrom(
          other.internalGetUserInfo());
      bitField0_ |= 0x00000200;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              userName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              password_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              locked_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              age_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              buf_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getSendTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              token_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureNameListIsMutable();
              nameList_.add(s);
              break;
            } // case 74
            case 82: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              userInfo__ = input.readMessage(
                  UserInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableUserInfo().getMutableMap().put(
                  userInfo__.getKey(), userInfo__.getValue());
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string user_name = 2;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string user_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      userName_ = getDefaultInstance().getUserName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string user_name = 2;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      password_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      password_ = getDefaultInstance().getPassword();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      password_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean locked_ ;
    /**
     * <code>bool locked = 4;</code>
     * @return The locked.
     */
    @java.lang.Override
    public boolean getLocked() {
      return locked_;
    }
    /**
     * <code>bool locked = 4;</code>
     * @param value The locked to set.
     * @return This builder for chaining.
     */
    public Builder setLocked(boolean value) {
      
      locked_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool locked = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocked() {
      bitField0_ = (bitField0_ & ~0x00000008);
      locked_ = false;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 5;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000010);
      age_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString buf_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes buf = 6;</code>
     * @return The buf.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBuf() {
      return buf_;
    }
    /**
     * <code>bytes buf = 6;</code>
     * @param value The buf to set.
     * @return This builder for chaining.
     */
    public Builder setBuf(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      buf_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bytes buf = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuf() {
      bitField0_ = (bitField0_ & ~0x00000020);
      buf_ = getDefaultInstance().getBuf();
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp sendTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     * @return Whether the sendTime field is set.
     */
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     * @return The sendTime.
     */
    public com.google.protobuf.Timestamp getSendTime() {
      if (sendTimeBuilder_ == null) {
        return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
      } else {
        return sendTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    public Builder setSendTime(com.google.protobuf.Timestamp value) {
      if (sendTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sendTime_ = value;
      } else {
        sendTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    public Builder setSendTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (sendTimeBuilder_ == null) {
        sendTime_ = builderForValue.build();
      } else {
        sendTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    public Builder mergeSendTime(com.google.protobuf.Timestamp value) {
      if (sendTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          sendTime_ != null &&
          sendTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getSendTimeBuilder().mergeFrom(value);
        } else {
          sendTime_ = value;
        }
      } else {
        sendTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    public Builder clearSendTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      sendTime_ = null;
      if (sendTimeBuilder_ != null) {
        sendTimeBuilder_.dispose();
        sendTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getSendTimeBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getSendTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
      if (sendTimeBuilder_ != null) {
        return sendTimeBuilder_.getMessageOrBuilder();
      } else {
        return sendTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp send_time = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getSendTimeFieldBuilder() {
      if (sendTimeBuilder_ == null) {
        sendTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSendTime(),
                getParentForChildren(),
                isClean());
        sendTime_ = null;
      }
      return sendTimeBuilder_;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>optional string token = 8;</code>
     * @return Whether the token field is set.
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string token = 8;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string token = 8;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string token = 8;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      token_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional string token = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      token_ = getDefaultInstance().getToken();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>optional string token = 8;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      token_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList nameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNameListIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        nameList_ = new com.google.protobuf.LazyStringArrayList(nameList_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @return A list containing the nameList.
     */
    public com.google.protobuf.ProtocolStringList
        getNameListList() {
      return nameList_.getUnmodifiableView();
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @return The count of nameList.
     */
    public int getNameListCount() {
      return nameList_.size();
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @param index The index of the element to return.
     * @return The nameList at the given index.
     */
    public java.lang.String getNameList(int index) {
      return nameList_.get(index);
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the nameList at the given index.
     */
    public com.google.protobuf.ByteString
        getNameListBytes(int index) {
      return nameList_.getByteString(index);
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @param index The index to set the value at.
     * @param value The nameList to set.
     * @return This builder for chaining.
     */
    public Builder setNameList(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNameListIsMutable();
      nameList_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @param value The nameList to add.
     * @return This builder for chaining.
     */
    public Builder addNameList(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNameListIsMutable();
      nameList_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @param values The nameList to add.
     * @return This builder for chaining.
     */
    public Builder addAllNameList(
        java.lang.Iterable<java.lang.String> values) {
      ensureNameListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, nameList_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNameList() {
      nameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name_list = 9;</code>
     * @param value The bytes of the nameList to add.
     * @return This builder for chaining.
     */
    public Builder addNameListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureNameListIsMutable();
      nameList_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> userInfo_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetUserInfo() {
      if (userInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserInfoDefaultEntryHolder.defaultEntry);
      }
      return userInfo_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableUserInfo() {
      if (userInfo_ == null) {
        userInfo_ = com.google.protobuf.MapField.newMapField(
            UserInfoDefaultEntryHolder.defaultEntry);
      }
      if (!userInfo_.isMutable()) {
        userInfo_ = userInfo_.copy();
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return userInfo_;
    }
    public int getUserInfoCount() {
      return internalGetUserInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    @java.lang.Override
    public boolean containsUserInfo(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetUserInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserInfoMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getUserInfo() {
      return getUserInfoMap();
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getUserInfoMap() {
      return internalGetUserInfo().getMap();
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    @java.lang.Override
    public long getUserInfoOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetUserInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    @java.lang.Override
    public long getUserInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetUserInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearUserInfo() {
      bitField0_ = (bitField0_ & ~0x00000200);
      internalGetMutableUserInfo().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    public Builder removeUserInfo(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableUserInfo().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableUserInfo() {
      bitField0_ |= 0x00000200;
      return internalGetMutableUserInfo().getMutableMap();
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    public Builder putUserInfo(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableUserInfo().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>map&lt;string, sint64&gt; user_info = 10;</code>
     */
    public Builder putAllUserInfo(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableUserInfo().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000200;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.UserRequest)
  }

  // @@protoc_insertion_point(class_scope:user.UserRequest)
  private static final com.zero.summer.pb.user.UserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zero.summer.pb.user.UserRequest();
  }

  public static com.zero.summer.pb.user.UserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserRequest>
      PARSER = new com.google.protobuf.AbstractParser<UserRequest>() {
    @java.lang.Override
    public UserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zero.summer.pb.user.UserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

